---
title: "SGLT2 QSP task"
subtitle: "PAGE 2026 AI workshop"
author: "M&S Decisions, `r Sys.Date()`"
output: 
    bookdown::html_document2:
      toc: true
      toc_depth: 5
      toc_float:
        collapsed: true
        smooth_scroll: false
      number_sections: true
      code_folding: hide
      fig_width: 10
      fig_height: 7
      fig_caption: true
      
    officedown::rdocx_document:
      reference_docx: document_template.docx
---

```{r load-packages-and-set-global-settings, include = TRUE, warning = FALSE, message = FALSE}
rm(list=ls())
set.seed(123456)

library(rxode2)
library(tidyverse)

theme_set(theme_bw())
theme_update(panel.grid.minor = element_blank())
MSDcol <- rep(c("#1a1866", "#f2b93b", "#b73b58", "#a2d630", "#5839bb", "#9c4ec7", "#3a6eba", "#efdd3c", "#69686d"), 10)
NEWcol <- c("dodgerblue", "seagreen2", "forestgreen", "orange2", "firebrick", "royalblue4",  "violetred1",  "black", "blue", "red", "purple", "gold", "skyblue3", "tan4", "plum2")

knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE, fig.cap = TRUE, fig.align = "center", results = 'hide') 
if (!knitr::is_html_output()) {knitr::opts_chunk$set(include = FALSE)}
if (!knitr::is_html_output()) {
run_num_tab <- run_autonum(seq_id = "Table", pre_label = "Table ", bkm = "anytable")
run_num_fig <- run_autonum(seq_id = "Figure", pre_label = "Figure ", bkm = "anyfigure")
}
```

```{r common-functions}
funSum_sim <- list(mean   = ~mean(., na.rm = T),
                   median = ~median(., na.rm = T),
                   min    = ~min(., na.rm = T),
                   max    = ~max(., na.rm = T),
                   sd     = ~sd(., na.rm = T), 
                   P025   = ~quantile(., 0.025, na.rm = T),
                   P05    = ~quantile(., 0.05, na.rm = T),
                   P10    = ~quantile(., 0.10, na.rm = T),
                   P15   = ~quantile(., 0.15, na.rm = T),
                   P25    = ~quantile(., 0.25, na.rm = T),
                   P75    = ~quantile(., 0.75, na.rm = T),
                   P85   = ~quantile(., 0.85, na.rm = T),
                   P90    = ~quantile(., 0.90, na.rm = T),
                   P95    = ~quantile(., 0.95, na.rm = T),
                   P975   = ~quantile(., 0.975, na.rm = T),
                   geom_mean = ~exp(mean(log(.), na.rm = T)),
                   CV     = ~sd(., na.rm = T)/mean(., na.rm = T)*100)

```

```{r import-data}

```

# Dataset exploration
```{r t-cov-dist, results = 'asis', tab.cap = "Disposition"}

```
  
# Model simulations  
```{r models}

```

```{r event-tables-and-parameters}

```

```{r simulations}

```

```{r p-sim-sd, fig.id = "p-sim-sd", fig.width = 8, fig.height = 6.5, fig.cap = "24-hour UGE after single dose"}

```

# R Runtime Environment {.tabset}
## Current R session {.unnumbered}
```{r sourcefile}
source_file <- basename(rstudioapi::getSourceEditorContext()$path)
```

**Source file:** `r source_file`
```{r rsession, results='asis'}
# Print a record of the environment in which this script was rendered
info <- sessionInfo()
```

```{r tab-rsession-env}
# R Version
info$R.version %>%
  as.data.frame() %>%
  select(version.string, platform) %>%
  rename(
    `R version` = version.string,
    Platform = platform
  ) %>%
  flextable() %>%
  set_table_properties(width = 1, layout = "autofit")
```

## Base Packages {.unnumbered}
```{r tab-rsession-base}
# Base Packages
tibble(Package = info$basePkgs) %>%
  arrange(Package) %>%
  flextable() %>% 
  set_table_properties(layout = "autofit", width = 0.4)
```

## Attached Packages {.unnumbered}
```{r tab-rsession-attached}
# Attached Packages
info$otherPkgs %>%
  purrr::map_dfr(~ tibble(Package = .x$Package, Version = .x$Version)) %>%
  arrange(Package) %>%
  flextable() %>%
  set_table_properties(layout = "autofit", width = 0.4)
```

## Loaded Packages {.unnumbered}
```{r tab-rsession-loaded}
# Loaded Packages
info$loadedOnly %>%
  purrr::map_dfr(~ tibble(Package = .x$Package, Version = .x$Version)) %>%
  arrange(Package) %>%
  flextable() %>%
  set_table_properties(layout = "autofit", width = 0.4)
```

## {-}